name: Cypress Gemobile Test
on:
  - push
  
jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: UI Cypress Teste Syscor
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: npm install       
      - name: Teste Syscor E2E Desktop Size
        run: npx cypress run --browser chrome
